# Generated by Django 5.0.4 on 2024-06-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dia', models.CharField(choices=[('Laborable', 'Laborable'), ('Festivos', 'Festivos'), ('Vacaciones', 'Vacaciones'), ('ILT', 'ILT'), ('Libre disposicion', 'Libre disposicion'), ('Ausencia justificadas', 'Ausencia justificadas'), ('Ausencia sin justificar', 'Ausencia sin justificar'), ('Otros', 'Otros')], max_length=50)),
                ('color', models.CharField(choices=[('Blue', 'blue'), ('Red', 'red'), ('Yellow', 'yellow'), ('Green', 'green'), ('Orange', 'orange'), ('Purple', 'purple'), ('Gray', 'gray'), ('Pink', 'pink')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.empleado')),
            ],
            options={
                'verbose_name': 'calendario',
                'verbose_name_plural': 'calendarios',
                'db_table': 'Calendarios',
                'ordering': ['anio', 'empleado', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_dia', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calendario.calendario')),
            ],
            options={
                'verbose_name': 'calendarioItem',
                'verbose_name_plural': 'calendarioItems',
                'db_table': 'CalendarioItem',
                'ordering': ['fecha', 'calendario'],
            },
        ),
    ]
